version: "3"

services:

  php:
    container_name: bitrix_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - bitrix_exam_network

  db:
    image: mysql:8
    container_name: bitrix_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bitrix_exam_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bitrix_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bitrix_exam_network

volumes:
  db_data:

networks:
  bitrix_exam_network:
